on:
  pull_request:
    branches:
      - master
    types: ["closed", "labeled"]

jobs:
  xealth-auto-cherry-pick:
    runs-on: ubuntu-latest
    name: Xealth Auto Cherry Picker
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Xealth Auto Cherry Pick
        uses: arivera-xealth/xealth-auto-cherry-pick@v1.0.3
        with:
          allowUserToSpecifyBranchViaLabel: 'true'
          labelPatternRequirement: 'CP v'
          userBranchPrefix: 'v'
          labels: |
            cherry-pick
          reviewers: |
            aReviewerUser
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}