name: Auto Cherry Pick
on:
  pull_request:
    branches:
      - master
    types: ["closed", "labeled"]
 
jobs:
  xealth-auto-cherry-pick:
    runs-on: ubuntu-latest
    name: Xealth Auto Cherry Picker
    if: github.event.pull_request.merged == true
    permissions:
      actions: read
      checks: read
      pull-requests: write
      statuses: read
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          fetch-depth: 0
      - name: test
        run: ls -la
      - name: Xealth Auto Cherry Pick
        uses: Xealth/cherry-pick-action@v1.0.0
        with:
          allowUserToSpecifyBranchViaLabel: 'true'
          labelPatternRequirement: 'CP v'
          userBranchPrefix: 'v'
          labels: |
            cherry-pick
          reviewers: |
            aReviewerUser
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}